export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_ALL_PRODUCTS = "SET_ALL_PRODUCTS";
